#!/bin/sh
#
# repmgrd     Start repmgrd daemon
#
# chkconfig: - 64 36
# description: repmgrd is a replication manager, and failover management tool for UxsinoDB

## BEGIN INIT INFO
# Provides: repmgrd
# Required-Start: $local_fs $remote_fs $network $syslog $named
# Required-Stop: $local_fs $remote_fs $network $syslog $named
# Should-Start: uxsinodb-9.6
# Short-Description: Start repmgrd daemon
# Description: repmgrd is replication manager, and failover management tool
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Find the name of the script
NAME=`basename $0`
if [ ${NAME:0:1} = "S" -o ${NAME:0:1} = "K" ]
then
       	NAME=${NAME:3}
fi

prog=repmgr
REPMGRD_LOCKFILE=/var/lock/subsys/$prog
REPMGRD_ENABLED=y
REPMGRD_OPTS=
REPMGRD_USER=uxdb
REPMGRD_HOME=/home/uxdb/uxdbinstall/dbsql/bin
REPMGRD_CONF=${REPMGRD_HOME}/repmgr.conf
REPMGRD_BIN=${REPMGRD_HOME}/repmgrd
REPMGRD=${REPMGRD_HOME}/repmgr
database_user=repmgr
database_name=repmgr
database_port=52025
ip_command_dir=/usr/sbin
arping_command_dir=/usr/sbin
REPMGRD_PIDFILE=/tmp/repmgrd.pid
VIP=10.1.106.173
MASK=255.255.0.0
VIP_eth=ens3
remote_hostname=node2
rewind_switch=on

# Get network config.
. /etc/sysconfig/network

# Read configuration variable file if it is present
[ -r /etc/sysconfig/repmgr/repmgr_service ] && . /etc/sysconfig/repmgr/repmgr_service

# For SELinux we need to use 'runuser' not 'su'
if [ -x /sbin/runuser ]
then
    SU=runuser
else
    SU=su
fi

test -x $REPMGRD_BIN || exit 0

case "$REPMGRD_ENABLED" in
    [Yy]*)
	break
	;;
    *)
	exit 0
	;;
esac

#if [ -z "${REPMGRD_OPTS}" ]
#then
#    echo "Not starting ${prog}, REPMGRD_OPTS not set in /etc/sysconfig/repmgr/repmgr-96"
#    exit 0
#fi
#数据库监控，数据库没有启动，启动数据库
database_monitor()
{
/etc/init.d/uxdb_service status 1>/dev/null 2>/dev/null
if [ $? -ne 0 ];then
        /etc/init.d/uxdb_service start 1>/dev/null 2>/dev/null
        echo "1"
else
        echo "0"
fi
}

#添加VIP,VIP存在则不添加VIP，不存在添加VIP
add_vip()
{
    ${ip_command_dir}/ip addr|grep $VIP
    if [ $? -eq 0 ];then
      echo -n 'repmgr start success'
      echo -n 'start failed: vip add failed,vip exists!'
      exit 1
    else
      ping $VIP -c 5 1>/dev/null 2>/dev/null
      if [ $? -eq 0 ];then
	  echo -n 'repmgr start success'
	  echo -n 'notice:vip add failed,vip is other host ip'
      else
          ${ip_command_dir}/ip addr add $VIP/$MASK dev ${VIP_eth} | ${arping_command_dir}/arping -I ${VIP_eth}  $VIP -w 1
      fi
    fi
}

#卸载VIP
del_vip()
{
    ${ip_command_dir}/ip addr|grep $VIP
    if [ $? == 0 ];then
      ${ip_command_dir}/ip addr del $VIP dev ${VIP_eth}
    fi
}

#判断主从
check_primary()
{
#判断主机个数
        primary_count=`${SU} -l $REPMGRD_USER -c "${REPMGRD} -f ${REPMGRD_CONF} cluster show|head -5 -|grep primary|wc -l"`
#主机个数为1，判断节点名是否为本机，如果是则添加VIP，不是则判断主机是否启动，规定时间内启动则启动repmgr，没有启动则退出
        if [ ${primary_count} -eq 1 ];then
                temp_node_name=`${SU} -l $REPMGRD_USER -c "${REPMGRD} -f ${REPMGRD_CONF} cluster show"|head -5 -|grep primary|awk -F '|' '{print $2}'|awk '{print $1}'`
                node_name=`hostname`
                if [ "${temp_node_name}" == "${node_name}" ];then
			${SU} -l $REPMGRD_USER -c "${REPMGRD_BIN} daemon start -f ${REPMGRD_CONF}"
			if [ $? -ne 0 ];then
				echo -n "start failed:repmgrd start is failed"	
				exit 1
			fi
                        add_vip
			echo -n "repmgr start success"
                else
                #echo "localhost is standby"
			for((i=1;i<=10;i++))	
			do
				${SU} -l $REPMGRD_USER -c "uxsql 'host = $remote_hostname user = $database_user dbname = $database_name port=$database_port connect_timeout = 10' -c 'select now();'" >/dev/null	
				if [ $? -eq 0 ];then
					break
				else
					sleep 10
				fi
			done
			if [ $i -eq 11 ];then
				echo -n "start failed:primary database is running"
				exit 1
			else
				${SU} -l $REPMGRD_USER -c "${REPMGRD_BIN} daemon start -f ${REPMGRD_CONF}"
                        	if [ $? -ne 0 ];then
                                	echo -n "start failed:repmgrd start is failed"  
					exit 1
				else
					echo -n "repmgr start success"
                        	fi
			fi
                fi
        else
#主机个数大于1，如果为真主添加VIP，如果为假主判断降为备机开关是否打开，打开则降为备机并启动repmgr，关闭则关闭数据库
                temp_node_name=`${SU} -l $REPMGRD_USER -c "${REPMGRD} -f ${REPMGRD_CONF} cluster show"|head -5 -|grep "running as primary"|awk -F '|' '{print $5}'|awk '{print $1}'`
                if [ "$temp_node_name" == "" ];then
			${SU} -l $REPMGRD_USER -c "${REPMGRD_BIN} daemon start -f ${REPMGRD_CONF}"
			if [ $? -ne 0 ];then
                                  echo -n "start failed:repmgrd start is failed"  
				  exit 1
                        fi
			add_vip
                else
			/etc/init.d/uxdb_service stop			
			if [ "${rewind_switch}" == "on" ];then
				${SU} -l $REPMGRD_USER -c "${REPMGRD} node rejoin -f ${REPMGRD_CONF} -d'host=${remote_hostname} dbname = $database_name user = $database_user' --force-rewind --config-files=uxsinodb.local.conf,uxsinodb.conf --verbose" 
				if [ $? -eq 0 ];then
					${SU} -l $REPMGRD_USER -c "${REPMGRD_BIN} daemon start -f ${REPMGRD_CONF}"
					if [ $? -ne 0 ];then
                                  		echo -n "start failed:repmgrd start is failed"  
                                  		exit 1
					else
						echo -n "repmgr start success"
                        		fi
				else
					echo -n "start failed:uxdb rewind failed"
					exit 1
				fi
			else
				echo -n "start failed:repmgr show cluster status exception"
				exit 1
			fi
		fi
        fi
}


# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 6
#启动函数,先监控数据库，链接本机数据库，规定时间内数据库启动则启动repmgr，没有启动则不启动repmgr
start(){
	database_monitor
	[ -x $REPMGRD_BIN ] || exit 5
	[ -f "${REPMGRD_CONF}" ] || exit 6
	echo -n "Starting $prog: "

	# Make sure startup-time log file is valid
        #mkdir -p $(dirname $REPMGRD_PIDFILE)
        #chown $REPMGRD_USER: $(dirname $REPMGRD_PIDFILE)

#	${SU} -l $REPMGRD_USER -c "${REPMGRD_BIN} -f ${REPMGR_CONF} ${REPMGRD_OPTS} -p ${REPMGRD_PIDFILE} >> ${REPMGRD_LOG} 2>&1" ${REPMGRD_USER} < /dev/null
	for((i=1;i<=10;i++))
	do
        	${SU} -l $REPMGRD_USER -c "uxsql 'user = $database_user dbname = $database_name port=$database_port connect_timeout = 10' -c 'select now();'" >/dev/null
                if [ $? -eq 0 ];then
                      break
                else
                      sleep 10
                fi
	done

	if [ $i -eq 11 ];then
		echo -n "start failed:because uxdb is not running"
		exit 1
	fi

	check_primary
	sleep 2
        retval=$?
	[ $retval -eq 0 ] && success
        echo
        [ $retval -eq 0 ] && touch $REPMGRD_LOCKFILE
        return $retval
}
#关闭服务，删除VIP，关闭repmgr,关闭数据库
stop(){
	del_vip
        echo -n "Stopping $prog: "
        killproc -p $REPMGRD_PIDFILE $prog -TERM
        retval=$?
	    /etc/init.d/uxdb_service stop
        echo
        [ $retval -eq 0 ] && rm -f $REPMGRD_LOCKFILE
        return $retval
}

restart(){
        if rh_status; then
                stop
		start
        else
                start
        fi
}
reload(){
        echo -n "Reloading $prog: "
        kill -HUP $(cat $REPMGRD_PIDFILE)
        retval=$?
        echo
        return $retval
}

rh_status() {
   if [ -f $REPMGRD_PIDFILE ] && [  `ps hp $(cat $REPMGRD_PIDFILE)|wc -l` -eq 1 ]
   then
       pid=$(cat $REPMGRD_PIDFILE)
       echo "Process repmgrd exists (PID $pid)"
       return 0
   else
       return 1
   fi
}

rh_status_q() {
        rh_status >/dev/null 2>&1
}
case "$1" in
  start)
        rh_status && exit 0
        start
        ;;
  stop)
        rh_status || exit 0
        stop
        ;;
  restart)
        restart
        ;;
  reload|force-reload)
        rh_status || exit 7
        reload
        ;;
  condrestart|try-restart)
        rh_status || exit 0
        restart
        ;;
  status)
	status -p $REPMGRD_PIDFILE repmgr-9.6
	script_result=$?

        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status}"
        exit 2
esac

exit $?
